resourcestring                                     {deutsch}
  capForm='Textebene aus PDF-Datei exportieren';
  capAddTxt='&Textebene exportieren';
  hntAddTxt='Eine oder mehrere PDF-Dateien auswählen';
  capInfo='&Info';
  hntInfo='Infodatei anzeigen.';
  errInfo=' fehlt.';
  hntInfofile='Diese Datei sollte im ZIP-Archiv dabei gewesen sein. Kopiere es in das Verzeichnis, wo das Tool "pdftotext" ist und versuche es nochmal zu laden.';
  capClose='&Beenden';
  hntClose='Programm beenden.';
  capOpenPDF='PDF-Dateien öffnen...';
  hntMemo='Ausgaben vom Terminal.';
  errPDF=' ist keine PDF-Datei.';
  hntBatch='Verbleib auf dieser Seite erlaubt, mehrere PDF-Dateien in einem Rutsch zu verarbeiten';
  hntPages='Die Einstellungen von der ersten Seite werden auch hier benutzt, um bestimmte Seiten (von-bis) aus folgender PDF-Datei zu verarbeiten';

  capBatch='Einstellungen/Batch';
  capPages='Seiten';
  capProt='Protokoll';
  capFrom='Seiten von';
  capTo='bis';
  capNumFiles='Anzahl PDF-Dateien: ';
  capProc='Verarbeitet: ';
  capAll='Alle &Seiten';
  capNotAll='Nur diese &Seiten';
  hntAll='Verarbeite alle Seiten dieser Datei';

  capLayout='Originales Layout';
  capRaw='Content stream order';
  capNopgbrk='Keine Seitenumbrüche';
  hntLayout='Maintain original physical layout';
  hntRaw='Keep strings in content stream order';
  hntNopgbrk='Keine Seitenumbrüche zwischen den Seiten einfügen';
  capOptional='Optionaler Parameter';
  hntOptional='Optionaler Parameter für "pdftotext" Kommandozeilentool';
  capPost='Nachbearbeitung';
  hntPost='Textlayer bearbeiten, um es fit für Übersetzung zu machen';

  hdrPDF='PDF-Datei:            ';
  hdrRaw='Textlayer roh:        ';
  hdrFin='Textlayer bearbeitet: ';


