resourcestring                                     {english}
  capForm='Export text layer from PDF file';
  capAddTxt='&Export text layer';
  hntAddTxt='Select one or more PDF files.';
  capInfo='&Info';
  hntInfo='Show info file.';
  errInfo=' missing.';
  hntInfofile='This file should be part of the original ZIP archive. Copy it to the directory where "pdftotext" tool is and try again.';
  capClose='&Quit';
  hntClose='Close the application.';
  capOpenPDF='Open PDF files ...';
  hntMemo='Terminal output.';
  errPDF=' is not a PDF file.';
  hntBatch='Remain at this page allows to process a couple of PDF files with one click.';
  hntPages='Keeps settings from Settings page to process pages of selected from following PDF file.';

  capBatch='Settings/Batch';
  capPages='Pages';
  capProt='Protocol';
  capFrom='Pages from';
  capTo='to';
  capNumFiles='Number PDF files: ';
  capProc='Processed: ';
  capAll='All pages';
  capNotAll='Only those pages';
  hntAll='Process all pages of this file';

  capLayout='Original layout';
  capRaw='Content stream order';
  capNopgbrk='No page breaks';
  hntLayout='Maintain original physical layout';
  hntRaw='Keep strings in content stream order';
  hntNopgbrk='Don''t insert page breaks between pages';
  capOptional='Optional parameter';
  hntOptional='Optional parameter for "pdftotext" command line tool';
  capPost='Post processing';
  hntPost='Post processing text layer to make it usable for translation';

  hdrPDF='PDF file:             ';
  hdrRaw='Text layer raw:       ';
  hdrFin='Text layer processed: ';


