resourcestring                                     {english}

  capForm='Add text layer to PDF file using "pdfsandwich"';
  capAddTxt='&Create text layer';
  hntAddTxt='Select one or more PDF files.';
  capInfo='&Info';
  hntInfo='Show info file.';
  errInfo='File "info.txt" missing.';
  hntInstall='See description in LINUX-Welt 01/2023, page 104 (in German).';
  capClose='&Quit';
  hntClose='Close the application.';
  capOpenPDF='Open scanned PDF files ...';
  hntMemo='Terminal output.';

