resourcestring                                     {english}
  sprache='eng';                                   {tesseract-ocr langauage code}

  capForm='Add text layer to PDF file using "pdfsandwich"';
  capAddTxt='&Create text layer';
  hntAddTxt='Select one or more PDF files.';
  capInfo='&Info';
  hntInfo='Show info file.';
  errInfo=' missing.';
  hntInfofile='This file should be part of the original ZIP archive. Copy it to the directory where "pdftext" tool is and try again.';
  capClose='&Quit';
  hntClose='Close the application.';
  capOpenPDF='Open scanned PDF files ...';
  hntMemo='Terminal output.';
  errPDF=' is not a PDF file.';

