resourcestring                                     {deutsch}
  sprache='deu';                                   {tesseract-ocr langauage code}

  capForm='Textebene zu PDF hinzufügen mit "pdfsandwich"';
  capAddTxt='&Textebene anlegen';
  hntAddTxt='Eine oder mehrere PDF-Dateien auswählen.';
  capInfo='&Info';
  hntInfo='Infodatei anzeigen.';
  errInfo=' fehlt.';
  hntInfofile='Diese Datei sollte im ZIP-Archiv dabei gewesen sein. Kopiere es in das Verzeichnis, wo das Tool "pdftext" ist und versuche es nochmal zu laden.';
  capClose='&Beenden';
  hntClose='Programm beenden.';
  capOpenPDF='Eingescannte PDF-Dateien öffnen...';
  hntMemo='Ausgaben vom Terminal.';
  errPDF=' ist keine PDF-Datei.';

