resourcestring                                     {deutsch}

  capForm='Textebene zu PDF hinzufügen mit "pdfsandwich"';
  capAddTxt='&Textebene anlegen';
  hntAddTxt='Eine oder mehrere PDF-Dateien auswählen.';
  capInfo='&Info';
  hntInfo='Infodatei anzeigen.';
  errInfo='Datei "info.txt" fehlt.';
  hntInstall='Bitte Vorgehensweise in LINUX-Welt 01/2023, Seite 104 nachlesen.';
  capClose='&Beenden';
  hntClose='Programm beenden.';
  capOpenPDF='Eingescannte PDF-Dateien öffnen...';
  hntMemo='Ausgaben vom Terminal.';

